pipeline{
    agent any

    stages {
        stage('Clonig Github repo to Jenkins'){
            steps{
                script{
                    echo 'Clonig Github repo to Jenkins..............'
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github-token', url: 'https://github.com/pareekpulkit/brainwave-basket.git']])
                    
                }
            }
        }
    }
}