pipeline{
    agent any

    environment{
        VENV_DIR = 'venv'
    }

    stages {
        stage('Clonig Github repo to Jenkins'){
            steps{
                script{
                    echo 'Clonig Github repo to Jenkins..............'
                    checkout scmGit(branches: [[name: '*/main']], extensions: [], userRemoteConfigs: [[credentialsId: 'github-token', url: 'https://github.com/pareekpulkit/brainwave-basket.git']])
                    
                }
            }
        }
        stage('Setting up our virtual Environment'){
            steps{
                script{
                    echo 'Setting up our virtual Environment..............'
                    sh '''
                    python -m virtualenv  ${VENV_DIR}
                    .${VENV_DIR}/bin/activate
                    pip install --upgrade pip 
                    pip install -e .
                    '''
                    
                }
            }
        }
    }
}