pipeline{
    agent any

    environment{
        VENV_DIR = 'venv'
        GCP_PROJECT = 'windy-renderer-467803-u4'
        GCLOUD_PATH = '/var/jenkins_home/google-cloud-sdk/bin'
    }

    stages {
        stage('Checkout with sparse checkout') {
            steps {
                // Checkout the repo as usual (downloads full .git history, but you’ll prune files next)
                checkout([$class: 'GitSCM',
                    branches: [[name: '*/main']],
                    userRemoteConfigs: [[
                        url: 'https://github.com/pareekpulkit/brainwave-basket.git',
                        credentialsId: 'github-token'
                    ]],
                    extensions: [
                        [$class: 'CleanBeforeCheckout'],
                    ]
                ])
                script {
                    // Enable sparse checkout after the repo is cloned
                    sh '''
                    git config core.sparseCheckout true
                    echo "Anime_Recommender_System/" > .git/info/sparse-checkout
                    git read-tree -mu HEAD
                    '''
                }
            }
        }
        
    }
}